# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Working Style Guide
email: felicia.artist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Working style guide and samples of past projects
url: "http://www.feliciachamberlain.com" 
twitter_username: felicitous_tech
github_username:  raison00

# Build settings
markdown: kramdown
